const $=id=>document.getElementById(id), KEY='zhoujian-v1';
const types={active:'主动收入',passive:'被动收入',expense:'支出'}, cats={active:['工资薪酬','自由职业','兼职收入','奖金','其他收入'],passive:['利息收益','投资分红','租金收入','版税收入','其他收益'],expense:['餐饮美食','日常购物','交通出行','居家生活','休闲娱乐','医疗健康','学习成长','其他支出']};
const icons={'餐饮美食':'♨','日常购物':'▣','交通出行':'↗','居家生活':'⌂','休闲娱乐':'♫','学习成长':'▤','工资薪酬':'▥','自由职业':'✎','利息收益':'✳','投资分红':'◈'};
const palette=['#557858','#99ad7d','#d8b58c','#bccbac','#dddcc0','#9baaa0','#caa48e','#c8cdba'];
function dateStr(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date());
function parseDate(s){return new Date(s+'T12:00:00')}
function shift(s,n){const d=parseDate(s);d.setDate(d.getDate()+n);return dateStr(d)}
function monday(s){return shift(s,-((parseDate(s).getDay()+6)%7))}
function fmt(c){return (c/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
const money=c=>'¥ '+fmt(c);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let week=monday(today()),view='report',entryType='expense',state={demo:false,budget:200000,records:[]};
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',3500)}
function weekRecords(){return state.records.filter(r=>r.date>=week&&r.date<=shift(week,6))}
function totals(rs){return rs.reduce((t,r)=>(t[r.type]+=r.cents,t),{active:0,passive:0,expense:0})}
function render(){const rs=weekRecords(),t=totals(rs),income=t.active+t.passive,balance=income-t.expense;const end=shift(week,6);$('week-label').textContent=`${week.replaceAll('-','.')} — ${end.slice(5).replace('-','.')}`;const wd=parseDate(shift(week,3)),year=wd.getFullYear(),jan4=monday(year+'-01-04');$('week-no').textContent=`${year} 年 · 第 ${Math.round((parseDate(week)-parseDate(jan4))/604800000)+1} 周`;
 $('active-total').textContent=money(t.active);$('passive-total').textContent=money(t.passive);$('expense-total').textContent=money(t.expense);$('balance-total').textContent=money(balance);$('expense-note').textContent=`共 ${rs.filter(r=>r.type==='expense').length} 笔支出 · 日均 ${money(Math.round(t.expense/7))}`;$('balance-note').textContent=income?`结余率 ${(balance/income*100).toFixed(1)}% · 收入减去支出`:'本周暂无收入记录';
 const grouping={};rs.filter(r=>r.type==='expense').forEach(r=>grouping[r.category]=(grouping[r.category]||0)+r.cents);const groups=Object.entries(grouping).sort((a,b)=>b[1]-a[1]);let pos=0;const gradient=groups.map(([c,v],i)=>{const a=pos;pos+=v/t.expense*100;return `${palette[i%palette.length]} ${a}% ${pos}%`}).join(',');$('donut-area').innerHTML=`<div class="donut" style="background:${groups.length?'conic-gradient('+gradient+')':'#edf1e8'}"><div class="donut-label">支出总额<b>${money(t.expense)}</b></div></div>`;$('category-list').innerHTML=groups.length?groups.map(([c,v],i)=>`<div class="category-line"><span><i style="background:${palette[i%palette.length]}"></i>${esc(c)}</span><b>${(v/t.expense*100).toFixed(1)}% · ${fmt(v)}</b></div>`).join(''):'<p class="muted">暂无支出，记下第一笔吧。</p>';
 const ratio=state.budget?t.expense/state.budget*100:0;$('budget-number').textContent=state.budget?ratio.toFixed(0)+'%':'未设置';$('budget-fill').style.width=Math.min(100,ratio)+'%';$('budget-fill').style.background=ratio>100?'#c4916e':'#91a67c';$('insight').textContent=rs.length?`${balance>=0?'本周结余 '+money(balance)+'。':'本周支出超出收入 '+money(-balance)+'。'}${groups.length?'最大支出是「'+groups[0][0]+'」，占总支出的 '+(groups[0][1]/t.expense*100).toFixed(0)+'%。':''}${ratio>100?' 已超出周预算 '+money(t.expense-state.budget)+'。':''}`:'这一周还是一张白纸。记下第一笔收支，周报会自动生成。';drawChart(rs);renderRows();$('budget-input').value=state.budget/100;
}
function drawChart(rs){const days=Array.from({length:7},(_,i)=>totals(rs.filter(r=>r.date===shift(week,i))));const max=Math.max(10000,...days.flatMap(t=>[t.active,t.passive,t.expense]));const ceiling=Math.ceil(max/4/10000)*40000;let svg='';for(let i=0;i<=4;i++){const y=175-i*38;svg+=`<line x1="46" y1="${y}" x2="680" y2="${y}" stroke="#edf0e8" stroke-dasharray="3 4"/><text x="36" y="${y+3}" text-anchor="end" fill="#a5ae9d" font-size="9">${Math.round(ceiling*i/4/100)}</text>`}days.forEach((t,i)=>{const x=74+i*88;['active','passive','expense'].forEach((k,j)=>{const h=t[k]/ceiling*152;svg+=`<rect x="${x+j*15}" y="${175-h}" width="10" height="${h}" rx="3" fill="${['#537a60','#b9cc9b','#ddb187'][j]}"><title>${shift(week,i)} ${types[k]}：${money(t[k])}</title></rect>`});svg+=`<text x="${x+20}" y="197" text-anchor="middle" fill="#7c8c73" font-size="10">${['周一','周二','周三','周四','周五','周六','周日'][i]}</text><text x="${x+20}" y="214" text-anchor="middle" fill="#a9b09f" font-size="8">${shift(week,i).slice(5).replace('-','/')}</text>`});$('chart').innerHTML=`<svg viewBox="0 0 700 225" role="img" aria-label="每天主动收入、被动收入和支出柱状图">${svg}</svg>`}
function renderRows(){let rs=view==='records'?state.records:weekRecords();const total=rs.length,q=$('search').value.trim().toLowerCase(),filter=$('filter').value;rs=rs.filter(r=>(filter==='all'||r.type===filter)&&[r.category,r.note,r.account].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));$('record-count').textContent=total+' 笔';$('filtered-count').textContent=`显示 ${rs.length} 笔记录`;$('rows').innerHTML=rs.length?rs.map(r=>`<tr><td>${esc(r.date.replaceAll('-','.'))}</td><td><div class="row-category"><span class="row-icon">${icons[r.category]||'◈'}</span><div>${esc(r.category)}<small>${esc(r.note||'无备注')}</small></div></div></td><td><span class="tag ${r.type}">${types[r.type]}</span></td><td>${esc(r.account)}</td><td class="number ${r.type==='expense'?'expense-num':'income-num'}">${r.type==='expense'?'−':'+'} ${money(r.cents)}</td><td class="row-actions"><button data-edit="${esc(r.id)}">编辑</button><button data-delete="${esc(r.id)}">删除</button></td></tr>`).join(''):'<tr><td class="empty" colspan="6">暂无记录 · 点击右上角「记一笔」开始</td></tr>'}
function setView(v){view=v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('report-view').hidden=v!=='report';$('records-section').hidden=v==='settings';$('settings-view').hidden=v!=='settings';$('crumb').textContent={report:'每周报表',records:'收支明细',settings:'偏好与备份'}[v];$('page-title').textContent={report:'这一周，心中有数 ✳',records:'每一笔，都有迹可循',settings:'你的账本，你来定义'}[v];$('page-desc').textContent={report:'用一份清晰的周报，看见收入、支出与生活的平衡。',records:'全部日期的收入与支出，随时搜索、修改和整理。',settings:'设置预算，备份数据，让记账成为安心的小习惯。'}[v];$('records-title').firstChild.textContent=v==='records'?'全部收支明细 ':'本周收支明细 ';$('export').hidden=v!=='report';render()}
function setType(t,category){entryType=t;document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('selected',b.dataset.type===t));$('category').innerHTML=cats[t].map(c=>`<option>${c}</option>`).join('');if(category)$('category').value=category}
function openEntry(id){if(!ready){toast('请等待账本加载完成');return}$('entry-form').reset();const r=id?state.records.find(r=>r.id===id):null;$('entry-id').value=r?.id||'';$('modal-title').textContent=r?'编辑记录':'记一笔';setType(r?.type||'expense',r?.category);$('date').value=r?.date||today();$('date').min='1900-01-01';$('date').max='2200-12-31';$('amount').value=r?r.cents/100:'';$('account').value=r?.account||'微信钱包';$('note').value=r?.note||'';$('entry-dialog').showModal();setTimeout(()=>$('amount').focus(),30)}
function download(content,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const userId=$('wallet-root').dataset.userId;
let cloud={records:[],budget:200000,version:0,updatedAt:null},pending=[],ready=false,syncing=false,conflict=null,localDb=null,durable=true,lastError='',sequence=0;
const storeName='zhoujian-cloud-v1';
function requestIdb(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function complete(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function openDb(){const req=indexedDB.open(storeName,1);req.onupgradeneeded=()=>{const db=req.result;db.createObjectStore('cache',{keyPath:'userId'});db.createObjectStore('queue',{keyPath:'key'})};localDb=await requestIdb(req)}
async function loadLocal(){if(!localDb)return;const tx=localDb.transaction(['cache','queue'],'readonly');const [cache,ops]=await Promise.all([requestIdb(tx.objectStore('cache').get(userId)),requestIdb(tx.objectStore('queue').getAll())]);if(cache&&cache.version>=cloud.version)cloud=cache;pending=ops.filter(o=>o.userId===userId).sort((a,b)=>a.sequence-b.sequence).map(o=>o.operation)}
async function cacheCloud(snapshot){cloud={records:snapshot.records,budget:snapshot.budget,version:snapshot.version,updatedAt:snapshot.updatedAt};if(!localDb)return;const tx=localDb.transaction('cache','readwrite'),store=tx.objectStore('cache');const old=await requestIdb(store.get(userId));if(!old||old.version<=snapshot.version)store.put({...cloud,userId});await complete(tx)}
async function putPending(op){if(localDb){const tx=localDb.transaction('queue','readwrite'),store=tx.objectStore('queue'),key=userId+':'+op.id;const old=await requestIdb(store.get(key));store.put({key,userId,sequence:old?.sequence??(Date.now()*1000+(sequence++%1000)),operation:op});await complete(tx)}else {const i=pending.findIndex(o=>o.id===op.id);if(i>=0)pending[i]=op;else pending.push(op)}}
async function removePending(id){if(localDb){const tx=localDb.transaction('queue','readwrite');tx.objectStore('queue').delete(userId+':'+id);await complete(tx)}pending=pending.filter(o=>o.id!==id)}
function project(){state={demo:false,records:cloud.records.map(r=>({...r})),budget:cloud.budget};for(const op of pending){if(op.kind==='budget')state.budget=op.budget;else if(op.kind==='delete')state.records=state.records.filter(r=>r.id!==op.recordId);else {const idx=state.records.findIndex(r=>r.id===op.record.id);if(idx>=0)state.records[idx]={...op.record};else state.records.push({...op.record})}}render();showStatus()}
function showStatus(){$('login-again').hidden=!lastError.includes('登录');const saved=document.querySelector('.save-state'),banner=$('sync-banner');const msg=conflict?'发现同一记录的修改冲突，请选择保留的版本':syncing?'正在与数据库同步…':lastError?lastError:pending.length?`${pending.length} 项变更保留在此设备，等待上传`:`已同步至云端数据库${cloud.updatedAt?' · '+new Date(cloud.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):' · 账本已准备好'}`;saved.textContent=conflict?'● 同步冲突':syncing?'● 正在同步':pending.length?'● '+pending.length+' 项待同步':lastError?'● 暂未连接':'● 已同步云端';$('sync-message').textContent=msg+(durable?'':' · 本机缓存不可用，请保持页面打开并导出备份');banner.classList.toggle('sync-error',Boolean(lastError||conflict||!durable));$('sync-now').disabled=syncing;$('add').disabled=!ready;$('conflict-panel').hidden=!conflict;if(conflict){const op=conflict.op,current=op.kind==='budget'?cloud.budget:cloud.records.find(r=>r.id===(op.record?.id||op.recordId));$('conflict-message').textContent=op.kind==='budget'?`预算冲突：此设备 ${money(op.budget)}，云端 ${money(cloud.budget)}。请选择要保留的版本。`:`${conflict.reason}。此设备：${op.record?op.record.date+' '+op.record.category+' '+money(op.record.cents)+' '+op.record.note:'删除此记录'}；云端：${current?current.date+' '+current.category+' '+money(current.cents)+' '+current.note:'已删除'}。`}}
async function enqueue(op){if(!ready){toast('请等待账本加载完成');return false}try{await putPending(op);await loadLocal();project();void sync();return true}catch{toast('此设备无法保存待同步记录，请导出备份并重试');return false}}
async function api(method='GET',body){
 const client=window.zhoujianSupabase;if(!client)throw Error('请先登录');
 const {data:sessionData}=await client.auth.getSession();if(!sessionData.session||sessionData.session.user.id!==userId)throw Error('登录已过期，请重新登录');
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{
  if(method==='GET'){const {data,error}=await client.from('zhoujian_ledgers').select('records,budget,version,updated_at').eq('user_id',userId).maybeSingle().abortSignal(controller.signal);if(error)throw Error('数据库读取失败，请确认已运行初始化 SQL');return {status:200,data:{records:data?.records||[],budget:data?.budget??200000,version:data?.version||0,updatedAt:data?.updated_at||null,userId}}}
  const {data,error}=await client.rpc('zhoujian_apply_operation',{op:body}).abortSignal(controller.signal);if(error)throw Error('数据库保存失败，请检查连接和数据库配置，记录仍保留在本机');return {status:data.conflict?409:200,data};
 }finally{clearTimeout(timer)}
}
async function doSync(){if(syncing||conflict)return;syncing=true;lastError='';showStatus();try{await loadLocal();const got=await api();if(got.status!==200)throw Error(got.data.error||'云端连接失败');await cacheCloud(got.data);ready=true;await loadLocal();project();let processed=0;while(pending.length&&processed++<1000){const op=pending[0],result=await api('POST',op);if(result.status===409){await cacheCloud(result.data);conflict={op,reason:result.data.error};project();return}if(result.status!==200)throw Error(result.data.error||'同步失败，记录仍保留在本机');await cacheCloud(result.data);await removePending(op.id);await loadLocal();project()}if(pending.length)toast('剩余记录将继续自动同步');else if(processed>0)toast('记录已保存到云端数据库')}catch(e){lastError=e.name==='AbortError'?'连接超时，待同步记录仍保留在此设备':e.message==='Failed to fetch'?'网络未连接，待同步记录仍保留在此设备':e.message||'同步失败，请重试';if(cloud.version||pending.length)ready=true}finally{syncing=false;project()}}
async function sync(){if(syncing||conflict)return;if(navigator.locks)await navigator.locks.request('zhoujian-sync-'+userId,{ifAvailable:true},async lock=>{if(lock)await doSync();else {await loadLocal();project()}});else await doSync()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>setType(b.dataset.type));$('add').onclick=()=>openEntry();$('close-modal').onclick=()=>$('entry-dialog').close();$('prev').onclick=()=>{week=shift(week,-7);render()};$('next').onclick=()=>{week=shift(week,7);render()};$('this-week').onclick=()=>{week=monday(today());render()};$('search').oninput=renderRows;$('filter').onchange=renderRows;$('sync-now').onclick=()=>void sync();document.querySelector('.save-state').onclick=()=>void sync();
$('entry-form').onsubmit=async e=>{e.preventDefault();const cents=Math.round(Number($('amount').value)*100),date=$('date').value;if(!Number.isSafeInteger(cents)||cents<=0||cents>99999999900||!/^\d{4}-\d{2}-\d{2}$/.test(date)||dateStr(parseDate(date))!==date||date<'1900-01-01'||date>'2200-12-31'){toast('请填写有效的金额和日期');return}const id=$('entry-id').value||crypto.randomUUID(),record={id,date,type:entryType,cents,category:$('category').value,account:$('account').value,note:$('note').value.trim()},base=state.records.find(r=>r.id===id)||null;const button=$('entry-form').querySelector('[type=submit]');button.disabled=true;try{if(await enqueue({id:crypto.randomUUID(),kind:'upsert',record,base})){week=monday(date);$('entry-dialog').close();project();if(pending.length)toast('记录已保留在此设备，正在上传')}}finally{button.disabled=false}};
$('rows').onclick=async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)openEntry(edit);if(del&&confirm('删除这笔记录？删除将同步到其他设备。')){const base=state.records.find(r=>r.id===del);if(base)await enqueue({id:crypto.randomUUID(),kind:'delete',recordId:del,base})}};
$('save-budget').onclick=async()=>{const n=Number($('budget-input').value);if(!Number.isFinite(n)||n<0||n>999999999){toast('请输入有效预算');return}await enqueue({id:crypto.randomUUID(),kind:'budget',budget:Math.round(n*100),baseBudget:state.budget})};
$('export').onclick=()=>{const rs=weekRecords().sort((a,b)=>a.date.localeCompare(b.date)),t=totals(rs);const cell=s=>'"'+String(s).replaceAll('"','""')+'"';const rows=[['周见个人财务周报',week+' 至 '+shift(week,6)],['主动收入',fmt(t.active)],['被动收入',fmt(t.passive)],['总收入',fmt(t.active+t.passive)],['总支出',fmt(t.expense)],['净结余',fmt(t.active+t.passive-t.expense)],['待同步变更数',pending.length],[],['日期','类型','分类','账户','金额(元)','备注'],...rs.map(r=>[r.date,types[r.type],r.category,r.account,(r.type==='expense'?-r.cents:r.cents)/100,r.note])];download('\ufeff'+rows.map(r=>r.map(s=>cell(typeof s==='string'&&/^[=+@\-]/.test(s)?"'"+s:s)).join(',')).join('\r\n'),`周见周报_${week}.csv`,'text/csv;charset=utf-8');toast('周报已导出')};
$('backup').onclick=()=>download(JSON.stringify({...state,version:1,pendingChanges:pending.length},null,2),'周见备份_'+today()+'.json','application/json');$('import').onclick=()=>$('import-file').click();
function validBackup(d){return d&&d.version===1&&Number.isSafeInteger(d.budget)&&d.budget>=0&&d.budget<=99999999900&&Array.isArray(d.records)&&d.records.length<=10000&&new Set(d.records.map(r=>r.id)).size===d.records.length&&d.records.every(r=>r&&typeof r.id==='string'&&/^[\w-]{1,100}$/.test(r.id)&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&dateStr(parseDate(r.date))===r.date&&r.date>='1900-01-01'&&r.date<='2200-12-31'&&Object.hasOwn(types,r.type)&&Number.isSafeInteger(r.cents)&&r.cents>0&&r.cents<=99999999900&&cats[r.type].includes(r.category)&&['微信钱包','支付宝','银行卡','现金','其他'].includes(r.account)&&typeof r.note==='string'&&r.note.length<=120)}
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!ready){toast('请等待账本加载完成');e.target.value='';return}try{if(file.size>10000000)throw Error();const data=JSON.parse(await file.text());if(!validBackup(data))throw Error();const exists=new Set(state.records.map(r=>r.id)),newRecords=data.records.filter(r=>!exists.has(r.id));if(!newRecords.length){toast('没有需要导入的新记录');return}if(confirm(`追加 ${newRecords.length} 笔记录到云端账本？${data.demo?' 此备份包含示例数据。':''}已有记录不会被覆盖。`)){const ops=newRecords.map(record=>({id:crypto.randomUUID(),kind:'upsert',record,base:null}));if(localDb){const tx=localDb.transaction('queue','readwrite'),store=tx.objectStore('queue');for(const operation of ops)store.put({key:userId+':'+operation.id,userId,sequence:Date.now()*1000+(sequence++%1000),operation});await complete(tx)}else pending.push(...ops);await loadLocal();project();toast('记录已加入同步队列');void sync()}}catch{toast('文件格式无效，请选择周见导出的 JSON 备份（最多一万笔）')}finally{e.target.value=''}};
$('choose-cloud').onclick=async()=>{if(!conflict)return;const target=conflict.op.record?.id||conflict.op.recordId;for(const op of [...pending])if(conflict.op.kind==='budget'?op.kind==='budget':(op.record?.id||op.recordId)===target)await removePending(op.id);conflict=null;await loadLocal();project();void sync()};
$('choose-local').onclick=async()=>{if(!conflict)return;if(!confirm('将此设备的这笔变更覆盖到云端，确定继续？'))return;const op={...conflict.op};if(op.kind==='budget')op.baseBudget=cloud.budget;else {op.base=cloud.records.find(r=>r.id===(op.record?.id||op.recordId))||null;if(op.kind==='delete'&&!op.base){await removePending(op.id);conflict=null;await loadLocal();project();void sync();return}}await putPending(op);conflict=null;await loadLocal();project();void sync()};
window.addEventListener('online',()=>void sync());window.addEventListener('focus',()=>void sync());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void sync()});window.addEventListener('beforeunload',e=>{if(pending.length&&!durable){e.preventDefault();e.returnValue=''}});setInterval(()=>{if(document.visibilityState==='visible')void sync()},30000);
async function boot(){showStatus();try{await openDb();await loadLocal();if(cloud.version||pending.length)ready=true}catch{durable=false}project();void sync()}
$('login-again').onclick=()=>{if(confirm('重新登录后，待上传记录仍保留在这台设备。继续？'))window.zhoujianSupabase.auth.signOut({scope:'local'})};
$('sign-out').onclick=async()=>{if(pending.length&&!confirm('此设备还有待同步记录，建议先完成同步。仍要退出登录吗？'))return;await window.zhoujianSupabase.auth.signOut({scope:'local'})};
void boot();

